apiVersion: v1
kind: ConfigMap
metadata:
  name: is-aruco-config
  namespace: default
data:
  config: |-
    {
      "broker_uri": "amqp://rabbitmq.default",
      "zipkin_uri": "http://zipkin.default",
      "config": {
        "cpu_parallelism": 0,
        "dictionary": "DICT_4X4_50",
        "lengths": {
          "0": 0.300
        }
      }
    }
---

apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  name: "is-aruco"
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: is-aruco
    spec:
      containers:
      - name: service 
        image: viros/is-aruco:0.0.3
        command: ["/service.bin"]
        args: ["/opt/options.json"]
        imagePullPolicy: Always
        resources:
          limits: 
            cpu: "1.0"
            memory: 256Mi
        volumeMounts:
          - name: options
            mountPath: /opt
      volumes:
      - name: options
        configMap:
          name: is-aruco-config
          items:
          - key: config
            path: options.json

---


apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: is-aruco
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: is-aruco
  minReplicas: 1
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 75
